type Condition =
  | "Sunny"
  | "Partly Cloudy"
  | "Cloudy"
  | "Overcast"
  | "Mist"
  | "Patchy rain nearby"
  | "Patchy snow nearby"
  | "Patchy sleet nearby"
  | "Patchy freezing drizzle nearby"
  | "Thundery outbreaks in nearby"
  | "Blowing snow"
  | "Blizzard"
  | "Fog"
  | "Freezing fog"
  | "Patchy light drizzle"
  | "Light drizzle"
  | "Freezing drizzle"
  | "Heavy freezing drizzle"
  | "Patchy light rain"
  | "Light rain"
  | "Moderate rain at times"
  | "Moderate rain"
  | "Heavy rain at times"
  | "Heavy rain"
  | "Light freezing rain"
  | "Moderate or heavy freezing rain"
  | "Light sleet"
  | "Moderate or heavy sleet"
  | "Patchy light snow"
  | "Light snow"
  | "Patchy moderate snow"
  | "Moderate snow"
  | "Patchy heavy snow"
  | "Heavy snow"
  | "Ice pellets"
  | "Light rain shower"
  | "Moderate or heavy rain shower"
  | "Torrential rain shower"
  | "Light sleet showers"
  | "Moderate or heavy sleet showers"
  | "Light snow showers"
  | "Moderate or heavy snow showers"
  | "Light showers of ice pellets"
  | "Moderate or heavy showers of ice pellets"
  | "Patchy light rain in area with thunder"
  | "Moderate or heavy rain in area with thunder"
  | "Patchy light snow in area with thunder"
  | "Moderate or heavy snow in area with thunder";

const requestData = {
  data: {
    location: {
      name: "Madison",
      region: "Wisconsin",
      country: "United States of America",
      lat: 43.07,
      lon: -89.4,
      tz_id: "America/Chicago",
      localtime_epoch: 1661362142,
      localtime: "2022-08-24 12:29",
    },
    current: {
      last_updated_epoch: 1661361300,
      last_updated: "2022-08-24 12:15",
      temp_c: 26.1,
      temp_f: 79,
      is_day: 1,
      condition: {
        text: "Partly cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
        code: 1003,
      },
      wind_mph: 6.9,
      wind_kph: 11.2,
      wind_degree: 200,
      wind_dir: "SSW",
      pressure_mb: 1018,
      pressure_in: 30.07,
      precip_mm: 0,
      precip_in: 0,
      humidity: 47,
      cloud: 75,
      feelslike_c: 27.6,
      feelslike_f: 81.7,
      vis_km: 16,
      vis_miles: 9,
      uv: 6,
      gust_mph: 5.8,
      gust_kph: 9.4,
    },
    forecast: {
      forecastday: [
        {
          date: "2022-08-24",
          date_epoch: 1661299200,
          day: {
            maxtemp_c: 29.3,
            maxtemp_f: 84.7,
            mintemp_c: 15.3,
            mintemp_f: 59.5,
            avgtemp_c: 21.2,
            avgtemp_f: 70.1,
            maxwind_mph: 7.4,
            maxwind_kph: 11.9,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 76,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "06:13 AM",
            sunset: "07:46 PM",
            moonrise: "03:05 AM",
            moonset: "06:57 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "10",
          },
          hour: [
            {
              time_epoch: 1661317200,
              time: "2022-08-24 00:00",
              temp_c: 17.1,
              temp_f: 62.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 250,
              wind_dir: "WSW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 83,
              cloud: 5,
              feelslike_c: 17.1,
              feelslike_f: 62.8,
              windchill_c: 17.1,
              windchill_f: 62.8,
              heatindex_c: 17.1,
              heatindex_f: 62.8,
              dewpoint_c: 14.2,
              dewpoint_f: 57.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 1,
            },
            {
              time_epoch: 1661320800,
              time: "2022-08-24 01:00",
              temp_c: 16.6,
              temp_f: 61.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 85,
              cloud: 5,
              feelslike_c: 16.6,
              feelslike_f: 61.9,
              windchill_c: 16.6,
              windchill_f: 61.9,
              heatindex_c: 16.6,
              heatindex_f: 61.9,
              dewpoint_c: 14.1,
              dewpoint_f: 57.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 1,
            },
            {
              time_epoch: 1661324400,
              time: "2022-08-24 02:00",
              temp_c: 16.2,
              temp_f: 61.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 255,
              wind_dir: "WSW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 88,
              cloud: 5,
              feelslike_c: 16.2,
              feelslike_f: 61.2,
              windchill_c: 16.2,
              windchill_f: 61.2,
              heatindex_c: 16.2,
              heatindex_f: 61.2,
              dewpoint_c: 14.1,
              dewpoint_f: 57.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
            {
              time_epoch: 1661328000,
              time: "2022-08-24 03:00",
              temp_c: 15.9,
              temp_f: 60.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 249,
              wind_dir: "WSW",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 89,
              cloud: 5,
              feelslike_c: 15.9,
              feelslike_f: 60.6,
              windchill_c: 15.9,
              windchill_f: 60.6,
              heatindex_c: 15.9,
              heatindex_f: 60.6,
              dewpoint_c: 14.1,
              dewpoint_f: 57.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 1,
            },
            {
              time_epoch: 1661331600,
              time: "2022-08-24 04:00",
              temp_c: 15.7,
              temp_f: 60.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 254,
              wind_dir: "WSW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 90,
              cloud: 5,
              feelslike_c: 15.7,
              feelslike_f: 60.3,
              windchill_c: 15.7,
              windchill_f: 60.3,
              heatindex_c: 15.7,
              heatindex_f: 60.3,
              dewpoint_c: 14,
              dewpoint_f: 57.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.1,
              gust_kph: 13,
              uv: 1,
            },
            {
              time_epoch: 1661335200,
              time: "2022-08-24 05:00",
              temp_c: 15.5,
              temp_f: 59.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 245,
              wind_dir: "WSW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 90,
              cloud: 5,
              feelslike_c: 15.5,
              feelslike_f: 59.9,
              windchill_c: 15.5,
              windchill_f: 59.9,
              heatindex_c: 15.5,
              heatindex_f: 59.9,
              dewpoint_c: 13.8,
              dewpoint_f: 56.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.6,
              gust_kph: 9,
              uv: 1,
            },
            {
              time_epoch: 1661338800,
              time: "2022-08-24 06:00",
              temp_c: 15.3,
              temp_f: 59.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.1,
              wind_kph: 5,
              wind_degree: 236,
              wind_dir: "WSW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 90,
              cloud: 6,
              feelslike_c: 15.3,
              feelslike_f: 59.5,
              windchill_c: 15.3,
              windchill_f: 59.5,
              heatindex_c: 15.3,
              heatindex_f: 59.5,
              dewpoint_c: 13.7,
              dewpoint_f: 56.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1,
            },
            {
              time_epoch: 1661342400,
              time: "2022-08-24 07:00",
              temp_c: 16,
              temp_f: 60.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 233,
              wind_dir: "SW",
              pressure_mb: 1017,
              pressure_in: 30.04,
              precip_mm: 0,
              precip_in: 0,
              humidity: 90,
              cloud: 5,
              feelslike_c: 16,
              feelslike_f: 60.8,
              windchill_c: 16,
              windchill_f: 60.8,
              heatindex_c: 16,
              heatindex_f: 60.8,
              dewpoint_c: 14.3,
              dewpoint_f: 57.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 5,
            },
            {
              time_epoch: 1661346000,
              time: "2022-08-24 08:00",
              temp_c: 18.2,
              temp_f: 64.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 231,
              wind_dir: "SW",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 83,
              cloud: 4,
              feelslike_c: 18.2,
              feelslike_f: 64.8,
              windchill_c: 18.2,
              windchill_f: 64.8,
              heatindex_c: 18.2,
              heatindex_f: 64.8,
              dewpoint_c: 15.3,
              dewpoint_f: 59.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 5,
            },
            {
              time_epoch: 1661349600,
              time: "2022-08-24 09:00",
              temp_c: 20.5,
              temp_f: 68.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 241,
              wind_dir: "WSW",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 76,
              cloud: 4,
              feelslike_c: 20.5,
              feelslike_f: 68.9,
              windchill_c: 20.5,
              windchill_f: 68.9,
              heatindex_c: 20.5,
              heatindex_f: 68.9,
              dewpoint_c: 16.2,
              dewpoint_f: 61.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.6,
              gust_kph: 9,
              uv: 6,
            },
            {
              time_epoch: 1661353200,
              time: "2022-08-24 10:00",
              temp_c: 22.5,
              temp_f: 72.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 237,
              wind_dir: "WSW",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 71,
              cloud: 4,
              feelslike_c: 24.8,
              feelslike_f: 76.6,
              windchill_c: 22.5,
              windchill_f: 72.5,
              heatindex_c: 24.8,
              heatindex_f: 76.6,
              dewpoint_c: 16.9,
              dewpoint_f: 62.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.6,
              gust_kph: 9,
              uv: 6,
            },
            {
              time_epoch: 1661356800,
              time: "2022-08-24 11:00",
              temp_c: 23.9,
              temp_f: 75,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 235,
              wind_dir: "SW",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 66,
              cloud: 3,
              feelslike_c: 25.5,
              feelslike_f: 77.9,
              windchill_c: 23.9,
              windchill_f: 75,
              heatindex_c: 25.5,
              heatindex_f: 77.9,
              dewpoint_c: 17.1,
              dewpoint_f: 62.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.8,
              gust_kph: 9.4,
              uv: 6,
            },
            {
              time_epoch: 1661360400,
              time: "2022-08-24 12:00",
              temp_c: 25,
              temp_f: 77,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 210,
              wind_dir: "SSW",
              pressure_mb: 1018,
              pressure_in: 30.05,
              precip_mm: 0,
              precip_in: 0,
              humidity: 61,
              cloud: 5,
              feelslike_c: 26.3,
              feelslike_f: 79.3,
              windchill_c: 25,
              windchill_f: 77,
              heatindex_c: 26.3,
              heatindex_f: 79.3,
              dewpoint_c: 17,
              dewpoint_f: 62.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.6,
              gust_kph: 9,
              uv: 7,
            },
            {
              time_epoch: 1661364000,
              time: "2022-08-24 13:00",
              temp_c: 28.8,
              temp_f: 83.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 204,
              wind_dir: "SSW",
              pressure_mb: 1017,
              pressure_in: 30.04,
              precip_mm: 0,
              precip_in: 0,
              humidity: 57,
              cloud: 3,
              feelslike_c: 30.6,
              feelslike_f: 87.1,
              windchill_c: 28.8,
              windchill_f: 83.8,
              heatindex_c: 30.6,
              heatindex_f: 87.1,
              dewpoint_c: 19.4,
              dewpoint_f: 66.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 7,
            },
            {
              time_epoch: 1661367600,
              time: "2022-08-24 14:00",
              temp_c: 29.3,
              temp_f: 84.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 196,
              wind_dir: "SSW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 5,
              feelslike_c: 31,
              feelslike_f: 87.8,
              windchill_c: 29.3,
              windchill_f: 84.7,
              heatindex_c: 31,
              heatindex_f: 87.8,
              dewpoint_c: 19.2,
              dewpoint_f: 66.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.8,
              gust_kph: 12.6,
              uv: 7,
            },
            {
              time_epoch: 1661371200,
              time: "2022-08-24 15:00",
              temp_c: 29.2,
              temp_f: 84.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 197,
              wind_dir: "SSW",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 9,
              feelslike_c: 30.8,
              feelslike_f: 87.4,
              windchill_c: 29.2,
              windchill_f: 84.6,
              heatindex_c: 30.8,
              heatindex_f: 87.4,
              dewpoint_c: 18.8,
              dewpoint_f: 65.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 7,
            },
            {
              time_epoch: 1661374800,
              time: "2022-08-24 16:00",
              temp_c: 26.9,
              temp_f: 80.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 199,
              wind_dir: "SSW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 55,
              cloud: 16,
              feelslike_c: 27.8,
              feelslike_f: 82,
              windchill_c: 26.9,
              windchill_f: 80.4,
              heatindex_c: 27.8,
              heatindex_f: 82,
              dewpoint_c: 17,
              dewpoint_f: 62.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 7,
            },
            {
              time_epoch: 1661378400,
              time: "2022-08-24 17:00",
              temp_c: 27.4,
              temp_f: 81.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 196,
              wind_dir: "SSW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 59,
              cloud: 4,
              feelslike_c: 28.8,
              feelslike_f: 83.8,
              windchill_c: 27.4,
              windchill_f: 81.3,
              heatindex_c: 28.8,
              heatindex_f: 83.8,
              dewpoint_c: 18.8,
              dewpoint_f: 65.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 7,
            },
            {
              time_epoch: 1661382000,
              time: "2022-08-24 18:00",
              temp_c: 27.7,
              temp_f: 81.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 196,
              wind_dir: "SSW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 68,
              cloud: 2,
              feelslike_c: 30.2,
              feelslike_f: 86.4,
              windchill_c: 27.7,
              windchill_f: 81.9,
              heatindex_c: 30.2,
              heatindex_f: 86.4,
              dewpoint_c: 21.4,
              dewpoint_f: 70.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.4,
              gust_kph: 11.9,
              uv: 7,
            },
            {
              time_epoch: 1661385600,
              time: "2022-08-24 19:00",
              temp_c: 24.7,
              temp_f: 76.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 188,
              wind_dir: "S",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 5,
              feelslike_c: 26.6,
              feelslike_f: 79.9,
              windchill_c: 24.7,
              windchill_f: 76.5,
              heatindex_c: 26.6,
              heatindex_f: 79.9,
              dewpoint_c: 20.5,
              dewpoint_f: 68.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.1,
              gust_kph: 13,
              uv: 6,
            },
            {
              time_epoch: 1661389200,
              time: "2022-08-24 20:00",
              temp_c: 20.2,
              temp_f: 68.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 185,
              wind_dir: "S",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 83,
              cloud: 8,
              feelslike_c: 20.2,
              feelslike_f: 68.4,
              windchill_c: 20.2,
              windchill_f: 68.4,
              heatindex_c: 20.2,
              heatindex_f: 68.4,
              dewpoint_c: 17.2,
              dewpoint_f: 63,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.6,
              gust_kph: 22,
              uv: 1,
            },
            {
              time_epoch: 1661392800,
              time: "2022-08-24 21:00",
              temp_c: 19.3,
              temp_f: 66.7,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 169,
              wind_dir: "S",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 86,
              cloud: 47,
              feelslike_c: 19.3,
              feelslike_f: 66.7,
              windchill_c: 19.3,
              windchill_f: 66.7,
              heatindex_c: 19.3,
              heatindex_f: 66.7,
              dewpoint_c: 16.8,
              dewpoint_f: 62.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1661396400,
              time: "2022-08-24 22:00",
              temp_c: 18.5,
              temp_f: 65.3,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 165,
              wind_dir: "SSE",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 87,
              cloud: 44,
              feelslike_c: 18.5,
              feelslike_f: 65.3,
              windchill_c: 18.5,
              windchill_f: 65.3,
              heatindex_c: 18.5,
              heatindex_f: 65.3,
              dewpoint_c: 16.3,
              dewpoint_f: 61.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15,
              gust_kph: 24.1,
              uv: 1,
            },
            {
              time_epoch: 1661400000,
              time: "2022-08-24 23:00",
              temp_c: 17.7,
              temp_f: 63.9,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 175,
              wind_dir: "S",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 89,
              cloud: 46,
              feelslike_c: 17.7,
              feelslike_f: 63.9,
              windchill_c: 17.7,
              windchill_f: 63.9,
              heatindex_c: 17.7,
              heatindex_f: 63.9,
              dewpoint_c: 15.8,
              dewpoint_f: 60.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
          ],
        },
        {
          date: "2022-08-25",
          date_epoch: 1661385600,
          day: {
            maxtemp_c: 24.3,
            maxtemp_f: 75.7,
            mintemp_c: 16.8,
            mintemp_f: 62.2,
            avgtemp_c: 20.1,
            avgtemp_f: 68.2,
            maxwind_mph: 7.6,
            maxwind_kph: 12.2,
            totalprecip_mm: 26.2,
            totalprecip_in: 1.03,
            avgvis_km: 9.1,
            avgvis_miles: 5,
            avghumidity: 88,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 89,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Heavy rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
              code: 1195,
            },
            uv: 5,
          },
          astro: {
            sunrise: "06:14 AM",
            sunset: "07:44 PM",
            moonrise: "04:08 AM",
            moonset: "07:28 PM",
            moon_phase: "Waning Crescent",
            moon_illumination: "3",
          },
          hour: [
            {
              time_epoch: 1661403600,
              time: "2022-08-25 00:00",
              temp_c: 17.3,
              temp_f: 63.1,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 214,
              wind_dir: "SW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 89,
              cloud: 49,
              feelslike_c: 17.3,
              feelslike_f: 63.1,
              windchill_c: 17.3,
              windchill_f: 63.1,
              heatindex_c: 17.3,
              heatindex_f: 63.1,
              dewpoint_c: 15.5,
              dewpoint_f: 59.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 1,
            },
            {
              time_epoch: 1661407200,
              time: "2022-08-25 01:00",
              temp_c: 17.5,
              temp_f: 63.5,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 251,
              wind_dir: "WSW",
              pressure_mb: 1018,
              pressure_in: 30.05,
              precip_mm: 0.2,
              precip_in: 0.01,
              humidity: 90,
              cloud: 89,
              feelslike_c: 17.5,
              feelslike_f: 63.5,
              windchill_c: 17.5,
              windchill_f: 63.5,
              heatindex_c: 17.5,
              heatindex_f: 63.5,
              dewpoint_c: 15.8,
              dewpoint_f: 60.4,
              will_it_rain: 0,
              chance_of_rain: 69,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 1,
            },
            {
              time_epoch: 1661410800,
              time: "2022-08-25 02:00",
              temp_c: 17.4,
              temp_f: 63.3,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 219,
              wind_dir: "SW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0.6,
              precip_in: 0.02,
              humidity: 93,
              cloud: 55,
              feelslike_c: 17.4,
              feelslike_f: 63.3,
              windchill_c: 17.4,
              windchill_f: 63.3,
              heatindex_c: 17.4,
              heatindex_f: 63.3,
              dewpoint_c: 16.2,
              dewpoint_f: 61.2,
              will_it_rain: 1,
              chance_of_rain: 89,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 1,
            },
            {
              time_epoch: 1661414400,
              time: "2022-08-25 03:00",
              temp_c: 17.2,
              temp_f: 63,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 266,
              wind_dir: "W",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0.8,
              precip_in: 0.03,
              humidity: 96,
              cloud: 65,
              feelslike_c: 17.2,
              feelslike_f: 63,
              windchill_c: 17.2,
              windchill_f: 63,
              heatindex_c: 17.2,
              heatindex_f: 63,
              dewpoint_c: 16.6,
              dewpoint_f: 61.9,
              will_it_rain: 1,
              chance_of_rain: 89,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.2,
              gust_kph: 18,
              uv: 1,
            },
            {
              time_epoch: 1661418000,
              time: "2022-08-25 04:00",
              temp_c: 17.1,
              temp_f: 62.8,
              is_day: 0,
              condition: {
                text: "Moderate rain",
                icon: "//cdn.weatherapi.com/weather/64x64/night/302.png",
                code: 1189,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 225,
              wind_dir: "SW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 5.5,
              precip_in: 0.22,
              humidity: 98,
              cloud: 77,
              feelslike_c: 17.1,
              feelslike_f: 62.8,
              windchill_c: 17.1,
              windchill_f: 62.8,
              heatindex_c: 17.1,
              heatindex_f: 62.8,
              dewpoint_c: 16.8,
              dewpoint_f: 62.2,
              will_it_rain: 1,
              chance_of_rain: 89,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 7,
              vis_miles: 4,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1,
            },
            {
              time_epoch: 1661421600,
              time: "2022-08-25 05:00",
              temp_c: 16.9,
              temp_f: 62.4,
              is_day: 0,
              condition: {
                text: "Light rain",
                icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
                code: 1183,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 184,
              wind_dir: "S",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 2.3,
              precip_in: 0.09,
              humidity: 99,
              cloud: 100,
              feelslike_c: 16.9,
              feelslike_f: 62.4,
              windchill_c: 16.9,
              windchill_f: 62.4,
              heatindex_c: 16.9,
              heatindex_f: 62.4,
              dewpoint_c: 16.7,
              dewpoint_f: 62.1,
              will_it_rain: 0,
              chance_of_rain: 69,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 1,
            },
            {
              time_epoch: 1661425200,
              time: "2022-08-25 06:00",
              temp_c: 16.8,
              temp_f: 62.2,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 123,
              wind_dir: "ESE",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 2.2,
              precip_in: 0.09,
              humidity: 99,
              cloud: 100,
              feelslike_c: 16.8,
              feelslike_f: 62.2,
              windchill_c: 16.8,
              windchill_f: 62.2,
              heatindex_c: 16.8,
              heatindex_f: 62.2,
              dewpoint_c: 16.6,
              dewpoint_f: 61.9,
              will_it_rain: 0,
              chance_of_rain: 59,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.1,
              gust_kph: 13,
              uv: 1,
            },
            {
              time_epoch: 1661428800,
              time: "2022-08-25 07:00",
              temp_c: 16.9,
              temp_f: 62.4,
              is_day: 1,
              condition: {
                text: "Heavy rain",
                icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
                code: 1195,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 126,
              wind_dir: "SE",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 11.4,
              precip_in: 0.45,
              humidity: 99,
              cloud: 82,
              feelslike_c: 16.9,
              feelslike_f: 62.4,
              windchill_c: 16.9,
              windchill_f: 62.4,
              heatindex_c: 16.9,
              heatindex_f: 62.4,
              dewpoint_c: 16.7,
              dewpoint_f: 62.1,
              will_it_rain: 1,
              chance_of_rain: 85,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 5,
              vis_miles: 3,
              gust_mph: 11.2,
              gust_kph: 18,
              uv: 4,
            },
            {
              time_epoch: 1661432400,
              time: "2022-08-25 08:00",
              temp_c: 17.5,
              temp_f: 63.5,
              is_day: 1,
              condition: {
                text: "Fog",
                icon: "//cdn.weatherapi.com/weather/64x64/day/248.png",
                code: 1135,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 141,
              wind_dir: "SE",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 97,
              cloud: 100,
              feelslike_c: 17.5,
              feelslike_f: 63.5,
              windchill_c: 17.5,
              windchill_f: 63.5,
              heatindex_c: 17.5,
              heatindex_f: 63.5,
              dewpoint_c: 17,
              dewpoint_f: 62.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 0,
              vis_miles: 0,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 4,
            },
            {
              time_epoch: 1661436000,
              time: "2022-08-25 09:00",
              temp_c: 19,
              temp_f: 66.2,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 161,
              wind_dir: "SSE",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 92,
              cloud: 96,
              feelslike_c: 19,
              feelslike_f: 66.2,
              windchill_c: 19,
              windchill_f: 66.2,
              heatindex_c: 19,
              heatindex_f: 66.2,
              dewpoint_c: 17.6,
              dewpoint_f: 63.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 4,
            },
            {
              time_epoch: 1661439600,
              time: "2022-08-25 10:00",
              temp_c: 20.6,
              temp_f: 69.1,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 175,
              wind_dir: "S",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 86,
              cloud: 98,
              feelslike_c: 20.6,
              feelslike_f: 69.1,
              windchill_c: 20.6,
              windchill_f: 69.1,
              heatindex_c: 20.6,
              heatindex_f: 69.1,
              dewpoint_c: 18.1,
              dewpoint_f: 64.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.7,
              gust_kph: 14,
              uv: 5,
            },
            {
              time_epoch: 1661443200,
              time: "2022-08-25 11:00",
              temp_c: 22.1,
              temp_f: 71.8,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 185,
              wind_dir: "S",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 79,
              cloud: 100,
              feelslike_c: 24.6,
              feelslike_f: 76.3,
              windchill_c: 22.1,
              windchill_f: 71.8,
              heatindex_c: 24.6,
              heatindex_f: 76.3,
              dewpoint_c: 18.4,
              dewpoint_f: 65.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.4,
              gust_kph: 11.9,
              uv: 5,
            },
            {
              time_epoch: 1661446800,
              time: "2022-08-25 12:00",
              temp_c: 23.2,
              temp_f: 73.8,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 196,
              wind_dir: "SSW",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 75,
              cloud: 100,
              feelslike_c: 25.2,
              feelslike_f: 77.4,
              windchill_c: 23.2,
              windchill_f: 73.8,
              heatindex_c: 25.2,
              heatindex_f: 77.4,
              dewpoint_c: 18.6,
              dewpoint_f: 65.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.8,
              gust_kph: 9.4,
              uv: 5,
            },
            {
              time_epoch: 1661450400,
              time: "2022-08-25 13:00",
              temp_c: 23.9,
              temp_f: 75,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 203,
              wind_dir: "SSW",
              pressure_mb: 1016,
              pressure_in: 29.99,
              precip_mm: 0.1,
              precip_in: 0,
              humidity: 73,
              cloud: 100,
              feelslike_c: 25.6,
              feelslike_f: 78.1,
              windchill_c: 23.9,
              windchill_f: 75,
              heatindex_c: 25.6,
              heatindex_f: 78.1,
              dewpoint_c: 18.7,
              dewpoint_f: 65.7,
              will_it_rain: 0,
              chance_of_rain: 69,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 3.1,
              gust_kph: 5,
              uv: 5,
            },
            {
              time_epoch: 1661454000,
              time: "2022-08-25 14:00",
              temp_c: 24,
              temp_f: 75.2,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 1.8,
              wind_kph: 2.9,
              wind_degree: 144,
              wind_dir: "SE",
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0.1,
              precip_in: 0,
              humidity: 73,
              cloud: 90,
              feelslike_c: 25.8,
              feelslike_f: 78.4,
              windchill_c: 24,
              windchill_f: 75.2,
              heatindex_c: 25.8,
              heatindex_f: 78.4,
              dewpoint_c: 18.9,
              dewpoint_f: 66,
              will_it_rain: 1,
              chance_of_rain: 78,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 2,
              gust_kph: 3.2,
              uv: 5,
            },
            {
              time_epoch: 1661457600,
              time: "2022-08-25 15:00",
              temp_c: 24.2,
              temp_f: 75.6,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 1.3,
              wind_kph: 2.2,
              wind_degree: 127,
              wind_dir: "SE",
              pressure_mb: 1015,
              pressure_in: 29.97,
              precip_mm: 0.1,
              precip_in: 0,
              humidity: 74,
              cloud: 67,
              feelslike_c: 25.9,
              feelslike_f: 78.6,
              windchill_c: 24.2,
              windchill_f: 75.6,
              heatindex_c: 25.9,
              heatindex_f: 78.6,
              dewpoint_c: 19.3,
              dewpoint_f: 66.7,
              will_it_rain: 1,
              chance_of_rain: 71,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 1.6,
              gust_kph: 2.5,
              uv: 5,
            },
            {
              time_epoch: 1661461200,
              time: "2022-08-25 16:00",
              temp_c: 24.3,
              temp_f: 75.7,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 0.2,
              wind_kph: 0.4,
              wind_degree: 67,
              wind_dir: "ENE",
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 0.6,
              precip_in: 0.02,
              humidity: 76,
              cloud: 63,
              feelslike_c: 26.1,
              feelslike_f: 79,
              windchill_c: 24.3,
              windchill_f: 75.7,
              heatindex_c: 26.1,
              heatindex_f: 79,
              dewpoint_c: 19.7,
              dewpoint_f: 67.5,
              will_it_rain: 1,
              chance_of_rain: 84,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 0.2,
              gust_kph: 0.4,
              uv: 5,
            },
            {
              time_epoch: 1661464800,
              time: "2022-08-25 17:00",
              temp_c: 24.2,
              temp_f: 75.6,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 337,
              wind_dir: "NNW",
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 77,
              cloud: 64,
              feelslike_c: 26.1,
              feelslike_f: 79,
              windchill_c: 24.2,
              windchill_f: 75.6,
              heatindex_c: 26.1,
              heatindex_f: 79,
              dewpoint_c: 20,
              dewpoint_f: 68,
              will_it_rain: 1,
              chance_of_rain: 75,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 3.6,
              gust_kph: 5.8,
              uv: 5,
            },
            {
              time_epoch: 1661468400,
              time: "2022-08-25 18:00",
              temp_c: 23.6,
              temp_f: 74.5,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 356,
              wind_dir: "N",
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 84,
              cloud: 75,
              feelslike_c: 25.6,
              feelslike_f: 78.1,
              windchill_c: 23.6,
              windchill_f: 74.5,
              heatindex_c: 25.6,
              heatindex_f: 78.1,
              dewpoint_c: 20.7,
              dewpoint_f: 69.3,
              will_it_rain: 0,
              chance_of_rain: 62,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 6,
              gust_kph: 9.7,
              uv: 5,
            },
            {
              time_epoch: 1661472000,
              time: "2022-08-25 19:00",
              temp_c: 21.9,
              temp_f: 71.4,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 355,
              wind_dir: "N",
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 1.7,
              precip_in: 0.07,
              humidity: 88,
              cloud: 80,
              feelslike_c: 21.9,
              feelslike_f: 71.4,
              windchill_c: 21.9,
              windchill_f: 71.4,
              heatindex_c: 24.5,
              heatindex_f: 76.1,
              dewpoint_c: 19.9,
              dewpoint_f: 67.8,
              will_it_rain: 1,
              chance_of_rain: 82,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 5,
            },
            {
              time_epoch: 1661475600,
              time: "2022-08-25 20:00",
              temp_c: 20,
              temp_f: 68,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 0,
              wind_dir: "N",
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 0,
              precip_in: 0,
              humidity: 92,
              cloud: 13,
              feelslike_c: 20,
              feelslike_f: 68,
              windchill_c: 20,
              windchill_f: 68,
              heatindex_c: 20,
              heatindex_f: 68,
              dewpoint_c: 18.7,
              dewpoint_f: 65.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 1,
            },
            {
              time_epoch: 1661479200,
              time: "2022-08-25 21:00",
              temp_c: 19.2,
              temp_f: 66.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 355,
              wind_dir: "N",
              pressure_mb: 1016,
              pressure_in: 29.99,
              precip_mm: 0,
              precip_in: 0,
              humidity: 93,
              cloud: 13,
              feelslike_c: 19.2,
              feelslike_f: 66.6,
              windchill_c: 19.2,
              windchill_f: 66.6,
              heatindex_c: 19.2,
              heatindex_f: 66.6,
              dewpoint_c: 18,
              dewpoint_f: 64.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 1,
            },
            {
              time_epoch: 1661482800,
              time: "2022-08-25 22:00",
              temp_c: 18.9,
              temp_f: 66,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 349,
              wind_dir: "N",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 93,
              cloud: 20,
              feelslike_c: 18.9,
              feelslike_f: 66,
              windchill_c: 18.9,
              windchill_f: 66,
              heatindex_c: 18.9,
              heatindex_f: 66,
              dewpoint_c: 17.7,
              dewpoint_f: 63.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 1,
            },
            {
              time_epoch: 1661486400,
              time: "2022-08-25 23:00",
              temp_c: 18.5,
              temp_f: 65.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 342,
              wind_dir: "NNW",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 93,
              cloud: 16,
              feelslike_c: 18.5,
              feelslike_f: 65.3,
              windchill_c: 18.5,
              windchill_f: 65.3,
              heatindex_c: 18.5,
              heatindex_f: 65.3,
              dewpoint_c: 17.3,
              dewpoint_f: 63.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 1,
            },
          ],
        },
        {
          date: "2022-08-26",
          date_epoch: 1661472000,
          day: {
            maxtemp_c: 25.5,
            maxtemp_f: 77.9,
            mintemp_c: 15.7,
            mintemp_f: 60.3,
            avgtemp_c: 20.3,
            avgtemp_f: 68.5,
            maxwind_mph: 6.7,
            maxwind_kph: 10.8,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            avgvis_km: 7.5,
            avgvis_miles: 4,
            avghumidity: 83,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            uv: 6,
          },
          astro: {
            sunrise: "06:15 AM",
            sunset: "07:43 PM",
            moonrise: "05:13 AM",
            moonset: "07:54 PM",
            moon_phase: "New Moon",
            moon_illumination: "0",
          },
          hour: [
            {
              time_epoch: 1661490000,
              time: "2022-08-26 00:00",
              temp_c: 17.9,
              temp_f: 64.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.6,
              wind_kph: 5.8,
              wind_degree: 339,
              wind_dir: "NNW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 93,
              cloud: 19,
              feelslike_c: 17.9,
              feelslike_f: 64.2,
              windchill_c: 17.9,
              windchill_f: 64.2,
              heatindex_c: 17.9,
              heatindex_f: 64.2,
              dewpoint_c: 16.8,
              dewpoint_f: 62.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 1,
            },
            {
              time_epoch: 1661493600,
              time: "2022-08-26 01:00",
              temp_c: 17.6,
              temp_f: 63.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.5,
              wind_kph: 4,
              wind_degree: 337,
              wind_dir: "NNW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 93,
              cloud: 8,
              feelslike_c: 17.6,
              feelslike_f: 63.7,
              windchill_c: 17.6,
              windchill_f: 63.7,
              heatindex_c: 17.6,
              heatindex_f: 63.7,
              dewpoint_c: 16.5,
              dewpoint_f: 61.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.1,
              gust_kph: 8.3,
              uv: 1,
            },
            {
              time_epoch: 1661497200,
              time: "2022-08-26 02:00",
              temp_c: 17.3,
              temp_f: 63.1,
              is_day: 0,
              condition: {
                text: "Mist",
                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                code: 1030,
              },
              wind_mph: 3.1,
              wind_kph: 5,
              wind_degree: 1,
              wind_dir: "N",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 94,
              cloud: 15,
              feelslike_c: 17.3,
              feelslike_f: 63.1,
              windchill_c: 17.3,
              windchill_f: 63.1,
              heatindex_c: 17.3,
              heatindex_f: 63.1,
              dewpoint_c: 16.3,
              dewpoint_f: 61.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 1,
            },
            {
              time_epoch: 1661500800,
              time: "2022-08-26 03:00",
              temp_c: 16.9,
              temp_f: 62.4,
              is_day: 0,
              condition: {
                text: "Mist",
                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                code: 1030,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 13,
              wind_dir: "NNE",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 95,
              cloud: 24,
              feelslike_c: 16.9,
              feelslike_f: 62.4,
              windchill_c: 16.9,
              windchill_f: 62.4,
              heatindex_c: 16.9,
              heatindex_f: 62.4,
              dewpoint_c: 16.1,
              dewpoint_f: 61,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 6.9,
              gust_kph: 11.2,
              uv: 1,
            },
            {
              time_epoch: 1661504400,
              time: "2022-08-26 04:00",
              temp_c: 16.5,
              temp_f: 61.7,
              is_day: 0,
              condition: {
                text: "Mist",
                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                code: 1030,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 14,
              wind_dir: "NNE",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 96,
              cloud: 32,
              feelslike_c: 16.5,
              feelslike_f: 61.7,
              windchill_c: 16.5,
              windchill_f: 61.7,
              heatindex_c: 16.5,
              heatindex_f: 61.7,
              dewpoint_c: 15.8,
              dewpoint_f: 60.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 1,
            },
            {
              time_epoch: 1661508000,
              time: "2022-08-26 05:00",
              temp_c: 16.1,
              temp_f: 61,
              is_day: 0,
              condition: {
                text: "Mist",
                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                code: 1030,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 16,
              wind_dir: "NNE",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 97,
              cloud: 39,
              feelslike_c: 16.1,
              feelslike_f: 61,
              windchill_c: 16.1,
              windchill_f: 61,
              heatindex_c: 16.1,
              heatindex_f: 61,
              dewpoint_c: 15.6,
              dewpoint_f: 60.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1,
            },
            {
              time_epoch: 1661511600,
              time: "2022-08-26 06:00",
              temp_c: 15.7,
              temp_f: 60.3,
              is_day: 0,
              condition: {
                text: "Fog",
                icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
                code: 1135,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 18,
              wind_dir: "NNE",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 97,
              cloud: 100,
              feelslike_c: 15.7,
              feelslike_f: 60.3,
              windchill_c: 15.7,
              windchill_f: 60.3,
              heatindex_c: 15.7,
              heatindex_f: 60.3,
              dewpoint_c: 15.3,
              dewpoint_f: 59.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 0,
              vis_miles: 0,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1,
            },
            {
              time_epoch: 1661515200,
              time: "2022-08-26 07:00",
              temp_c: 16,
              temp_f: 60.8,
              is_day: 1,
              condition: {
                text: "Fog",
                icon: "//cdn.weatherapi.com/weather/64x64/day/248.png",
                code: 1135,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 29,
              wind_dir: "NNE",
              pressure_mb: 1017,
              pressure_in: 30.04,
              precip_mm: 0,
              precip_in: 0,
              humidity: 98,
              cloud: 100,
              feelslike_c: 16,
              feelslike_f: 60.8,
              windchill_c: 16,
              windchill_f: 60.8,
              heatindex_c: 16,
              heatindex_f: 60.8,
              dewpoint_c: 15.7,
              dewpoint_f: 60.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 0,
              vis_miles: 0,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 4,
            },
            {
              time_epoch: 1661518800,
              time: "2022-08-26 08:00",
              temp_c: 17.7,
              temp_f: 63.9,
              is_day: 1,
              condition: {
                text: "Mist",
                icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
                code: 1030,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 40,
              wind_dir: "NE",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 95,
              cloud: 65,
              feelslike_c: 17.7,
              feelslike_f: 63.9,
              windchill_c: 17.7,
              windchill_f: 63.9,
              heatindex_c: 17.7,
              heatindex_f: 63.9,
              dewpoint_c: 16.8,
              dewpoint_f: 62.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 8.3,
              gust_kph: 13.3,
              uv: 4,
            },
            {
              time_epoch: 1661522400,
              time: "2022-08-26 09:00",
              temp_c: 19.4,
              temp_f: 66.9,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 52,
              wind_dir: "NE",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 89,
              cloud: 65,
              feelslike_c: 19.4,
              feelslike_f: 66.9,
              windchill_c: 19.4,
              windchill_f: 66.9,
              heatindex_c: 19.4,
              heatindex_f: 66.9,
              dewpoint_c: 17.5,
              dewpoint_f: 63.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.9,
              gust_kph: 11.2,
              uv: 4,
            },
            {
              time_epoch: 1661526000,
              time: "2022-08-26 10:00",
              temp_c: 21.2,
              temp_f: 70.2,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 49,
              wind_dir: "NE",
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0,
              precip_in: 0,
              humidity: 81,
              cloud: 40,
              feelslike_c: 21.2,
              feelslike_f: 70.2,
              windchill_c: 21.2,
              windchill_f: 70.2,
              heatindex_c: 24.3,
              heatindex_f: 75.7,
              dewpoint_c: 17.9,
              dewpoint_f: 64.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.7,
              gust_kph: 10.8,
              uv: 6,
            },
            {
              time_epoch: 1661529600,
              time: "2022-08-26 11:00",
              temp_c: 23,
              temp_f: 73.4,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 53,
              wind_dir: "NE",
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 49,
              feelslike_c: 25,
              feelslike_f: 77,
              windchill_c: 23,
              windchill_f: 73.4,
              heatindex_c: 25,
              heatindex_f: 77,
              dewpoint_c: 18.1,
              dewpoint_f: 64.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 6,
            },
            {
              time_epoch: 1661533200,
              time: "2022-08-26 12:00",
              temp_c: 24.1,
              temp_f: 75.4,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 55,
              wind_dir: "NE",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 70,
              cloud: 70,
              feelslike_c: 25.8,
              feelslike_f: 78.4,
              windchill_c: 24.1,
              windchill_f: 75.4,
              heatindex_c: 25.8,
              heatindex_f: 78.4,
              dewpoint_c: 18.2,
              dewpoint_f: 64.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 5,
            },
            {
              time_epoch: 1661536800,
              time: "2022-08-26 13:00",
              temp_c: 25.2,
              temp_f: 77.4,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 61,
              wind_dir: "ENE",
              pressure_mb: 1018,
              pressure_in: 30.05,
              precip_mm: 0,
              precip_in: 0,
              humidity: 66,
              cloud: 34,
              feelslike_c: 26.6,
              feelslike_f: 79.9,
              windchill_c: 25.2,
              windchill_f: 77.4,
              heatindex_c: 26.6,
              heatindex_f: 79.9,
              dewpoint_c: 18.4,
              dewpoint_f: 65.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.9,
              gust_kph: 11.2,
              uv: 7,
            },
            {
              time_epoch: 1661540400,
              time: "2022-08-26 14:00",
              temp_c: 25.5,
              temp_f: 77.9,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 60,
              wind_dir: "ENE",
              pressure_mb: 1017,
              pressure_in: 30.04,
              precip_mm: 0,
              precip_in: 0,
              humidity: 62,
              cloud: 68,
              feelslike_c: 26.8,
              feelslike_f: 80.2,
              windchill_c: 25.5,
              windchill_f: 77.9,
              heatindex_c: 26.8,
              heatindex_f: 80.2,
              dewpoint_c: 17.6,
              dewpoint_f: 63.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.2,
              gust_kph: 11.5,
              uv: 6,
            },
            {
              time_epoch: 1661544000,
              time: "2022-08-26 15:00",
              temp_c: 25.5,
              temp_f: 77.9,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 65,
              wind_dir: "ENE",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 61,
              cloud: 54,
              feelslike_c: 26.7,
              feelslike_f: 80.1,
              windchill_c: 25.5,
              windchill_f: 77.9,
              heatindex_c: 26.7,
              heatindex_f: 80.1,
              dewpoint_c: 17.5,
              dewpoint_f: 63.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.4,
              gust_kph: 11.9,
              uv: 7,
            },
            {
              time_epoch: 1661547600,
              time: "2022-08-26 16:00",
              temp_c: 25.4,
              temp_f: 77.7,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 80,
              wind_dir: "E",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 63,
              cloud: 44,
              feelslike_c: 26.7,
              feelslike_f: 80.1,
              windchill_c: 25.4,
              windchill_f: 77.7,
              heatindex_c: 26.7,
              heatindex_f: 80.1,
              dewpoint_c: 17.8,
              dewpoint_f: 64,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.7,
              gust_kph: 10.8,
              uv: 7,
            },
            {
              time_epoch: 1661551200,
              time: "2022-08-26 17:00",
              temp_c: 25.4,
              temp_f: 77.7,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 87,
              wind_dir: "E",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 63,
              cloud: 37,
              feelslike_c: 26.7,
              feelslike_f: 80.1,
              windchill_c: 25.4,
              windchill_f: 77.7,
              heatindex_c: 26.7,
              heatindex_f: 80.1,
              dewpoint_c: 17.7,
              dewpoint_f: 63.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 7,
            },
            {
              time_epoch: 1661554800,
              time: "2022-08-26 18:00",
              temp_c: 24.6,
              temp_f: 76.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 101,
              wind_dir: "ESE",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              humidity: 70,
              cloud: 0,
              feelslike_c: 26.2,
              feelslike_f: 79.2,
              windchill_c: 24.6,
              windchill_f: 76.3,
              heatindex_c: 26.2,
              heatindex_f: 79.2,
              dewpoint_c: 18.8,
              dewpoint_f: 65.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 6,
            },
            {
              time_epoch: 1661558400,
              time: "2022-08-26 19:00",
              temp_c: 22.4,
              temp_f: 72.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 111,
              wind_dir: "ESE",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 78,
              cloud: 0,
              feelslike_c: 24.7,
              feelslike_f: 76.5,
              windchill_c: 22.4,
              windchill_f: 72.3,
              heatindex_c: 24.7,
              heatindex_f: 76.5,
              dewpoint_c: 18.3,
              dewpoint_f: 64.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 6,
            },
            {
              time_epoch: 1661562000,
              time: "2022-08-26 20:00",
              temp_c: 19.6,
              temp_f: 67.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 125,
              wind_dir: "SE",
              pressure_mb: 1017,
              pressure_in: 30.04,
              precip_mm: 0,
              precip_in: 0,
              humidity: 84,
              cloud: 0,
              feelslike_c: 19.6,
              feelslike_f: 67.3,
              windchill_c: 19.6,
              windchill_f: 67.3,
              heatindex_c: 19.6,
              heatindex_f: 67.3,
              dewpoint_c: 16.8,
              dewpoint_f: 62.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
            {
              time_epoch: 1661565600,
              time: "2022-08-26 21:00",
              temp_c: 18.5,
              temp_f: 65.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 127,
              wind_dir: "SE",
              pressure_mb: 1018,
              pressure_in: 30.05,
              precip_mm: 0,
              precip_in: 0,
              humidity: 89,
              cloud: 0,
              feelslike_c: 18.5,
              feelslike_f: 65.3,
              windchill_c: 18.5,
              windchill_f: 65.3,
              heatindex_c: 18.5,
              heatindex_f: 65.3,
              dewpoint_c: 16.6,
              dewpoint_f: 61.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.2,
              gust_kph: 18,
              uv: 1,
            },
            {
              time_epoch: 1661569200,
              time: "2022-08-26 22:00",
              temp_c: 17.9,
              temp_f: 64.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 124,
              wind_dir: "SE",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 92,
              cloud: 0,
              feelslike_c: 17.9,
              feelslike_f: 64.2,
              windchill_c: 17.9,
              windchill_f: 64.2,
              heatindex_c: 17.9,
              heatindex_f: 64.2,
              dewpoint_c: 16.6,
              dewpoint_f: 61.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.3,
              gust_kph: 19.8,
              uv: 1,
            },
            {
              time_epoch: 1661572800,
              time: "2022-08-26 23:00",
              temp_c: 17.3,
              temp_f: 63.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 126,
              wind_dir: "SE",
              pressure_mb: 1018,
              pressure_in: 30.06,
              precip_mm: 0,
              precip_in: 0,
              humidity: 94,
              cloud: 0,
              feelslike_c: 17.3,
              feelslike_f: 63.1,
              windchill_c: 17.3,
              windchill_f: 63.1,
              heatindex_c: 17.3,
              heatindex_f: 63.1,
              dewpoint_c: 16.3,
              dewpoint_f: 61.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 1,
            },
          ],
        },
      ],
    },
    isLoading: false,
  },
} as const;

type CurrentKeys = keyof typeof requestData;
export type CurrentWeatherType = typeof requestData[CurrentKeys] & {
  error?: { message: string };
};
